Remove extra spaces.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -40,7 +40,7 @@ if [[ ! $no_verify -eq 1 ]]; then
 fi
 
 if [[ ! $no_extract -eq 1 ]]; then
-	extract_ruby   || fail "Unpacking of $ruby_archive failed!"
+	extract_ruby || fail "Unpacking of $ruby_archive failed!"
 fi
 
 download_patches || fail "Fetching patches $patches failed!"
@@ -55,7 +55,7 @@ install_ruby   || fail "Installation of $ruby $ruby_version failed!"
 post_install   || fail "Post-install tasks failed!"
 
 if [[ $cleanup -eq 1 ]]; then
-	cleanup_source  || fail "Cleanup of archive and unpacked source in $src_dir/ failed!"
+	cleanup_source || fail "Cleanup of archive and unpacked source in $src_dir/ failed!"
 fi
 
 log "Successfully installed $ruby $ruby_version into $install_dir"
