Rename all variables to lower-case to match variable naming convention.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -10,34 +10,34 @@ fi
 parse_options "$@" || exit $?
 load_ruby          || exit $?
 
-if [[ $NO_REINSTALL -eq 1 ]] && [[ -x "$INSTALL_DIR/bin/ruby" ]]; then
-	log "Ruby is already installed into $INSTALL_DIR"
+if [[ $no_reinstall -eq 1 ]] && [[ -x "$install_dir/bin/ruby" ]]; then
+	log "Ruby is already installed into $install_dir"
 	exit
 fi
 
-log "Installing $RUBY $RUBY_VERSION into $INSTALL_DIR ..."
+log "Installing $ruby $ruby_version into $install_dir ..."
 
 pre_install || fail "Pre-install tasks failed!"
 
-if [[ ! $NO_INSTALL_DEPS -eq 1 ]]; then
+if [[ ! $no_install_deps -eq 1 ]]; then
 	install_deps || fail "Installing dependencies failed!"
 fi
 
-if [[ ! $NO_DOWNLOAD -eq 1 ]]; then
-	download_ruby || fail "Download of $RUBY_URL failed!"
+if [[ ! $no_download -eq 1 ]]; then
+	download_ruby || fail "Download of $ruby_url failed!"
 fi
 
-if [[ ! $NO_VERIFY -eq 1 ]]; then
-	verify_ruby || fail "Verification of of $RUBY_ARCHIVE failed!"
+if [[ ! $no_verify -eq 1 ]]; then
+	verify_ruby || fail "Verification of of $ruby_archive failed!"
 fi
 
-extract_ruby   || fail "Unpacking of $RUBY_ARCHIVE failed!"
-download_patches || fail "Fetching patches $PATCHES failed!"
-apply_patches  || fail "Patching $RUBY $RUBY_VERSION failed!"
-cd "$SRC_DIR/$RUBY_SRC_DIR"
-configure_ruby || fail "Configuration of $RUBY $RUBY_VERSION failed!"
-compile_ruby   || fail "Compiling $RUBY $RUBY_VERSION failed!"
-install_ruby   || fail "Installation of $RUBY $RUBY_VERSION failed!"
+extract_ruby   || fail "Unpacking of $ruby_archive failed!"
+download_patches || fail "Fetching patches $patches failed!"
+apply_patches  || fail "Patching $ruby $ruby_version failed!"
+cd "$src_dir/$ruby_src_dir"
+configure_ruby || fail "Configuration of $ruby $ruby_version failed!"
+compile_ruby   || fail "Compiling $ruby $ruby_version failed!"
+install_ruby   || fail "Installation of $ruby $ruby_version failed!"
 post_install   || fail "Post-install tasks failed!"
 
-log "Successfully installed $RUBY $RUBY_VERSION into $INSTALL_DIR"
+log "Successfully installed $ruby $ruby_version into $install_dir"
