Moved NO_* checks into bin.
* bin/ruby-install should manage the control flow.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -18,10 +18,20 @@ fi
 
 log "Installing $RUBY $RUBY_VERSION into $INSTALL_DIR ..."
 
-pre_install    || fail "Pre-install tasks failed!"
-install_deps   || fail "Installing dependencies failed!"
-download_ruby  || fail "Download of $RUBY_URL failed!"
-verify_ruby    || fail "Verification of of $RUBY_ARCHIVE failed!"
+pre_install || fail "Pre-install tasks failed!"
+
+if [[ $NO_INSTALL_DEPS -eq 1 ]]; then
+	install_deps || fail "Installing dependencies failed!"
+fi
+
+if [[ $NO_DOWNLOAD -eq 1 ]]; then
+	download_ruby || fail "Download of $RUBY_URL failed!"
+fi
+
+if [[ $NO_VERIFY -eq 1 ]]; then
+	verify_ruby || fail "Verification of of $RUBY_ARCHIVE failed!"
+fi
+
 extract_ruby   || fail "Unpacking of $RUBY_ARCHIVE failed!"
 apply_patches  || fail "Patching $RUBY $RUBY_VERSION failed!"
 configure_ruby || fail "Configuration of $RUBY $RUBY_VERSION failed!"
