Move $binary_install checks to bin/ruby-install
configure/clean/compile should never be necessary for binary rubies.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -35,9 +35,13 @@ extract_ruby   || fail "Unpacking of $ruby_archive failed!"
 download_patches || fail "Fetching patches $patches failed!"
 apply_patches  || fail "Patching $ruby $ruby_version failed!"
 cd "$src_dir/$ruby_src_dir"
-configure_ruby || fail "Configuration of $ruby $ruby_version failed!"
-clean_ruby     || fail "Cleaning $ruby $ruby_version failed!"
-compile_ruby   || fail "Compiling $ruby $ruby_version failed!"
+
+if [[ ! $binary_install -eq 1 ]]; then
+	configure_ruby || fail "Configuration of $ruby $ruby_version failed!"
+	clean_ruby     || fail "Cleaning $ruby $ruby_version failed!"
+	compile_ruby   || fail "Compiling $ruby $ruby_version failed!"
+fi
+
 install_ruby   || fail "Installation of $ruby $ruby_version failed!"
 post_install   || fail "Post-install tasks failed!"
 
