Add --cleanup option.
Adds an optional --cleanup option flag to remove the downloaded archive and any unpacked source, as suggested in #116.

diff --git a/bin/ruby-install b/bin/ruby-install
--- a/bin/ruby-install
+++ b/bin/ruby-install
@@ -40,4 +40,8 @@ compile_ruby   || fail "Compiling $ruby $ruby_version failed!"
 install_ruby   || fail "Installation of $ruby $ruby_version failed!"
 post_install   || fail "Post-install tasks failed!"
 
+if [[ $cleanup -eq 1 ]]; then
+	cleanup_source  || fail "Cleanup of archive and unpacked source in $src_dir/ failed!"
+fi
+
 log "Successfully installed $ruby $ruby_version into $install_dir"
